---

- name: Apt proxy configuration is present
  when: syskit_apt_proxy
  template:
    src: apt.j2
    dest: /etc/apt/apt.conf.d/proxy
    mode: "644"
    owner: root
    group: root

- name: Apt proxy configuration is absent
  when: not syskit_apt_proxy
  file:
    path: /etc/apt/apt.conf.d/proxy
    state: absent
