---

# prep ferm.d/

- name: Ferm module directory is present
  when: syskit_ferm_rules
  file:
    path: /etc/ferm.d
    state: directory
    owner: root
    group: adm
    mode: "750"

- name: Ferm default module is present
  when: syskit_ferm_rules
  command: mv /etc/ferm/ferm.conf /etc/ferm.d/default
  args:
    creates: /etc/ferm.d/default
  notify: syskit_reload_ferm

- name: Ferm is configured
  when: syskit_ferm_rules
  copy:
    content: "@include '/etc/ferm.d/';"
    dest: /etc/ferm/ferm.conf
    owner: root
    group: adm
    mode: "644"
    backup: yes
  notify: syskit_reload_ferm

# unprep ferm.d/

- name: Move back default module as main configuration
  when: not syskit_ferm_rules
  command: mv /etc/ferm.d/default /etc/ferm/ferm.conf
  args:
    removes: /etc/ferm.d/default
  notify: syskit_reload_ferm

- name: Ferm module directory is absent
  when: not syskit_ferm_rules
  command: rmdir /etc/ferm.d
  args:
    removes: /etc/ferm.d

################################################################################

- name: Ferm rules are present
  with_items: syskit_ferm_rules
  when: item.state == "present"
  template:
    src: ferm.j2
    dest: "/etc/ferm.d/{{ item.name }}"
    owner: root
    group: adm
    mode: "644"
  notify: syskit_reload_ferm

- name: Ferm rules are absent
  with_items: syskit_ferm_rules
  when: item.state == "absent"
  file:
    path: "/etc/ferm.d/{{ item.name }}"
    state: absent
