---

- name: Ferm module directory is present
  file:
    path: /etc/ferm.d
    state: directory
    owner: root
    group: adm
    mode: "750"

- name: Assess ferm default module
  stat:
    path: /etc/ferm.d/default
  register: ferm_default
  changed_when: no

- name: Ferm default module is present
  command: mv /etc/ferm/ferm.conf /etc/ferm.d/default
  when: not ferm_default.stat.exists
  notify: syskit_reload_ferm

- name: Ferm is configured
  copy:
    content: "@include '/etc/ferm.d/';"
    dest: /etc/ferm/ferm.conf
    owner: root
    group: adm
    mode: "644"
  notify: syskit_reload_ferm

- name: Ferm modules are absent
  file:
    path: "/etc/ferm.d/{{ item.name }}"
    state: absent
  when: item.state == "absent"
  with_items: syskit_ferm_modules

- name: Ferm modules are present
  template:
    src: ferm.j2
    dest: "/etc/ferm.d/{{ item.name }}"
    owner: root
    group: adm
    mode: "644"
  when: item.state == "present"
  with_items: syskit_ferm_modules
  notify: syskit_reload_ferm
