---

# TODO: if there's no rule and ferm.d/ is empty, collapse it back to the default layout?

- name: Ferm module directory is present
  file:
    path: /etc/ferm.d
    state: directory
    owner: root
    group: adm
    mode: "750"

- name: Assess ferm default module
  register: ferm_default
  stat:
    path: /etc/ferm.d/default
  changed_when: no

- name: Ferm default module is present
  when: not ferm_default.stat.exists
  command: mv /etc/ferm/ferm.conf /etc/ferm.d/default
  notify: syskit_reload_ferm

- name: Ferm is configured
  copy:
    content: "@include '/etc/ferm.d/';"
    dest: /etc/ferm/ferm.conf
    owner: root
    group: adm
    mode: "644"
  notify: syskit_reload_ferm

- name: Ferm modules are absent
  with_items: syskit_ferm_rules
  when: item.state == "absent"
  file:
    path: "/etc/ferm.d/{{ item.name }}"
    state: absent

- name: Ferm modules are present
  with_items: syskit_ferm_rules
  when: item.state == "present"
  template:
    src: ferm.j2
    dest: "/etc/ferm.d/{{ item.name }}"
    owner: root
    group: adm
    mode: "644"
  notify: syskit_reload_ferm
