---

############
# packages #
############ 

# install logrotate if any module is defined
- name: Logrotate package is present
  when: syskit_logrotate_modules
  apt:
    name: logrotate
    state: present
    update_cache: yes
    cache_valid_time: 3600

# purge nginx if no site is defined and autopurge is set
- name: Logrotate package is absent
  when: not syskit_logrotate_modules and syskit_logrotate_autopurge
  apt:
    name: logrotate
    state: absent
    purge: yes

###########
# modules #
###########

- name: Logrotate module directory is present
  file:
    path: /etc/logrotate.d
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Logrotate modules are absent
  with_items: syskit_logrotate_modules
  when: item.state == "absent"
  file:
    path: "/etc/logrotate.d/{{ item.name }}"
    state: absent

- name: Logrotate modules are present
  with_items: syskit_logrotate_modules
  when: item.state == "present"
  template:
    src: logrotate.j2
    dest: '/etc/logrotate.d/{{ item.name }}'
    owner: root
    group: root
    mode: "644"
