---

- name: Logrotate module directory is present
  file:
    path: /etc/logrotate.d
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Logrotate modules are present
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/{{ item.name }}
    owner: root
    group: root
    mode: "644"
  with_items: debkit_logrotate_modules