---

# app present

- name: MacOS app defaults are present
  with_items: "{{ syskit_macos_apps }}"
  when: item.state == "present" and item.defaults
  copy:
    src: "{{ item.defaults }}"
    dest: ~/Library/Preferences/

- name: MacOS app is present
  with_items: "{{ syskit_macos_apps }}"
  when: item.state == "present"
  macos_app:
    name: "{{ item.name }}"
    state: present

# app absent

- name: MacOS app is absent
  with_items: "{{ syskit_macos_apps }}"
  when: item.state == "absent"
  macos_app:
    name: "{{ item.name }}"
    state: absent

- name: MacOS app defaults are absent
  with_subelements:
  - "{{ syskit_macos_apps }}"
  - domains
  when: item.0.state == "absent"
  macos_defaults:
    domain: "{{ item.1 }}"
    state: absent

- name: MacOS app extra preferences are absent
  with_subelements:
  - "{{ syskit_macos_apps }}"
  - domains
  when: item.0.state == "absent"
  file:
    path: ~/Library/Preferences/{{ item.1 }}
    state: absent

- name: MacOS app support is absent
  with_items: "{{ syskit_macos_apps }}"
  when: item.state == "absent"
  file:
    path: ~/Library/MacOS app Support/{{ item.name }}
    state: absent

- name: MacOS app container is absent
  with_subelements:
  - "{{ syskit_macos_apps }}"
  - domains
  when: item.0.state == "absent"
  file:
    path: ~/Library/Containers/{{ item.1 }}
    state: absent

- name: MacOS app package is absent
  with_subelements:
  - "{{ syskit_macos_apps }}"
  - domains
  when: item.0.state == "absent"
  macos_pkg:
    name: "{{ item.1 }}"
    state: absent
