---

############
# packages #
############ 

# install nginx if any site is defined
- name: Nginx package is present
  when: syskit_nginx_sites
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600

# purge nginx if no site is defined and autopurge is set
- name: Nginx package is absent
  when: not syskit_nginx_sites and syskit_nginx_autopurge
  apt:
    name: nginx
    state: absent
    purge: yes

################
# certificates #
################

- name: Nginx certs are present
  with_items: syskit_nginx_sites
  when: item.state == "present" and item.server.tls
  file:
    src: "{{ item.crtpath }}"
    dest: "/etc/ssl/certs/{{ item.server.name }}.crt"
    mode: "644"
    owner: root
    group: root

- name: Nginx certs are absent
  with_items: syskit_nginx_sites
  when: item.state == "absent" and item.server.tls
  file:
    path: "/etc/ssl/certs/{{ item.server.name }}.crt"
    state: absent

- name: Nginx keys are present
  with_items: syskit_nginx_sites
  when: item.state == "present" and item.server.tls
  file:
    content: "{{ item.server.tls.keyval }}"
    dest: "/etc/ssl/private/{{ item.server.name }}.key"
    mode: "640"
    owner: root
    group: ssl-cert

- name: Nginx keys are absent
  with_items: syskit_nginx_sites
  when: item.state == "absent" and item.server.tls
  file:
    path: "/etc/ssl/private/{{ item.server.name }}.key"
    state: absent

#########
# sites #
#########

- name: Nginx available sites are present
  with_items: syskit_nginx_sites
  when: item.state == "present"
  template:
    src: nginx.j2
    dest: "/etc/nginx/sites-available/{{ item.server.name }}"
    owner: www-data
    group: www-data

- name: Nginx available sites are absent
  with_items: syskit_nginx_sites
  when: item.state == "absent"
  file:
    path: "/etc/nginx/sites-available/{{ item.server.name }}"
    state: absent

- name: Nginx sites are enabled
  with_items: syskit_nginx_sites
  when: item.enabled
  file:
    src: "/etc/nginx/sites-available/{{ item.server.name }}"
    dest: "/etc/nginx/sites-enabled/{{ item.server.name }}"
    state: link
    owner: www-data
    group: www-data
  notify:
  - syskit_reload_nginx

- name: Nginx sites are disabled
  with_items: syskit_nginx_sites
  when: not item.enabled
  file:
    path: "/etc/nginx/sites-enabled/{{ item.server.name }}"
    state: absent
  notify:
  - syskit_reload_nginx

###########
# service #
###########

- name: nginx service is started
  when: syskit_nginx_sites
  service:
    name: nginx
    state: started
    enabled: yes
