---

- name: Rsyslog forwarding configuration is present
  when: syskit_logforward.tcp or syskit_logforward.udp
  template:
    src: rsyslog.j2
    dest: /etc/rsyslog.d/forward.conf
    mode: "644"
    owner: root
    group: root
  notify:
  - syskit_reload_rsyslog
