---

# NOTE!
# Restarting the ferm service is not sufficient
# service: name=ferm state=restarted
# If you want to do it, flush its cache first /var/cache/ferm/* with:
# command: find /var/cache/ferm -mindepth 1 -delete
- name: syskit_reload_ferm
  command: ferm /etc/ferm/ferm.conf

- name: syskit_reload_nginx
  service:
    name: nginx
    state: reloaded

- name: syskit_reload_rsyslog
  service:
    name: rsyslog
    state: reloaded
